library("dplyr")
hpc<-read.table("household_power_consumption.txt", sep=";", header = TRUE)
hpc[[1]]<-as.Date(hpc[[1]],"%d/%m/%Y")
Date1<-as.Date("01/02/2007","%d/%m/%Y")
Date2<-as.Date("02/02/2007","%d/%m/%Y")
data<-filter(hpc, Date >= Date1 & Date <= Date2)
data[[3]]<-as.numeric(as.character(data[[3]]))
png("Plot2.png", width=480, height=480)
plot(data$Global_active_power,type="l",xlab="",ylab="Global Active Power (kilowatts)",axes=FALSE)
axis(side=1,at=c(0,1440,2880),labels=c("Thu","Fri","Sat"))
axis(side=2,at=c(0,2,4,6,8),labels = c("0","2","4","6",""))
box()
dev.off()
