library("dplyr")
hpc<-read.table("household_power_consumption.txt", sep=";", header = TRUE)
hpc[[1]]<-as.Date(hpc[[1]],"%d/%m/%Y")
Date1<-as.Date("01/02/2007","%d/%m/%Y")
Date2<-as.Date("02/02/2007","%d/%m/%Y")
data<-filter(hpc, Date >= Date1 & Date <= Date2)
data[[8]]<-as.numeric(as.character(data[[8]]))
data[[7]]<-as.numeric(as.character(data[[7]]))
png("Plot3.png", width=480, height=480)
plot(data$Sub_metering_1,type="l",col="black",xlab="",ylab="Energy sub metering",axes=FALSE)
lines(data$Sub_metering_2,col="red")
lines(data$Sub_metering_3,col="blue")
axis(side=1,at=c(0,1440,2880,3000),labels=c("Thu","Fri","Sat",""))
axis(side=2,at=c(0,10,20,30,40),labels = c("0","10","20","30",""))
legend("topright",lty=1,col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),text.width = 800)
box()
dev.off()
